linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  ColorVariable:
    enabled: false

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: false

  PlaceholderInExtend:
    enabled: true

  HexNotation:
    enabled: false

  HexLength:
    enabled: false

  ImportantRule:
    enabled: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character:  space
    width: 2

  PropertySortOrder:
    enabled: false

  SelectorFormat:
    enabled: false

  Comment:
    enabled: false

  BorderZero:
    enabled: false

  LeadingZero:
    style: include_zero

  SelectorDepth:
    enabled: true
    max_depth: 6

  NestingDepth:
    enabled: true
    max_depth: 6

  SingleLinePerProperty:
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: false

  StringQuotes:
    style: double_quotes

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlQuotes:
    enabled: true

  VendorPrefix:
    enabled: true

  ZeroUnit:
    enabled: true

  VariableForProperty:
    enabled: true
    properties:
      - font
